services:
  # PostgreSQL Database
  arzuamber-db:
    image: postgres:latest
    container_name: arzuamber-db
    ports:
      - 5435:5432  # Host portu ile container portunu eşliyoruz
    environment:
      - POSTGRES_USER=arzuamber_user
      - POSTGRES_PASSWORD=arzuamber_pass
      - POSTGRES_DB=arzuamber-db
    networks:
      - my-network
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Veritabanı verilerinin kalıcı olması için volume kullanıyoruz

  # MinIO (Blob Storage)
  minio:
    image: 'bitnami/minio:latest'
    container_name: arzuamber-blob-storage
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=arzuamber_user
      - MINIO_ROOT_PASSWORD=arzuamber_pass
    volumes:
      - minio_data:/data
    networks:
      - my-network

  # Spring Boot Application
  arzuamber-api:
    build:
      context: .
    container_name: arzuamber-api
    depends_on:
      - arzuamber-db
      - minio
    ports:
      - 9090:8080
    networks:
      - my-network


networks:
  my-network:
    driver: bridge  # Aynı ağda çalışan servisler birbirine erişebilsin

volumes:
  minio_data:
    driver: local
  postgres_data:
    driver: local  # PostgreSQL veritabanı verilerinin kalıcı olması için volume kullanıyoruz