services:
  # PostgreSQL Database
  arzuamber-db:
    image: postgres:latest
    container_name: arzuamber-db
    ports:
      - "5435:5432"  # Host portu ile container portunu eşliyoruz
    environment:
      - POSTGRES_USER=arzuamber_user
      - POSTGRES_PASSWORD=arzuamber_pass
      - POSTGRES_DB=arzuamber-db
    networks:
      - my-network
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # Veritabanı verilerini hostta sakla
    restart: unless-stopped  # Sistem yeniden başlarsa veri kaybolmaz

  # MinIO (Blob Storage)
  minio:
    image: 'bitnami/minio:latest'
    container_name: arzuamber-blob-storage
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=arzuamber_user
      - MINIO_ROOT_PASSWORD=arzuamber_pass
      - MINIO_STORAGE_CLASS_STANDARD=EC:2
    volumes:
      - ./minio_data:/data  # MinIO verilerini hostta sakla
    networks:
      - my-network
    restart: unless-stopped

  # Spring Boot Application
  arzuamber-api:
    build:
      context: .
    container_name: arzuamber-api
    depends_on:
      - arzuamber-db
      - minio
    ports:
      - "9090:8080"
    networks:
      - my-network
    restart: unless-stopped

networks:
  my-network:
    driver: bridge  # Aynı ağda çalışan servisler birbirine erişebilsin