services:
  arzuamber:
    image: postgres
    container_name: arzuamber-db
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=arzuamber_user
      - POSTGRES_PASSWORD=arzuamber_pass
      - POSTGRES_DB=arzuamber-db
    networks:
      - my-network

  minio:
    image: 'bitnami/minio:latest'
    container_name: arzuamber-blob-storage
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=arzuamber_user
      - MINIO_ROOT_PASSWORD=arzuamber_pass
    volumes:
      - minio_data:/data
    networks:
      - my-network

networks:
  my-network:

volumes:
  minio_data:
    driver: local