spring:
  application:
    name: arzuamber

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/arzuamber-db
    username: arzuamber_user
    password: arzuamber_pass
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

  jwt:
    secret_keys: "RDDCT6me8cETAsAiABsYc0FwzLlu4CcNJWMBV8OdGt8Qrt2hleK1W/p/9K8kJuaNcqnsVgZ6PvfR2QcshYBGBqH3MJVekOHlQoyM9VspWkYFNovzBn/QOPiHyLGsaDhB/KIUleVCaMJK3YktQavVvGsFbld1QYXqnkeLZ9jb5tw="
    expiration: 7200000
    refresh-token:
      expiration: 604800000

  minio:
    url: http://localhost:9000
    user: arzuamber_user
    password: arzuamber_pass
    bucket-name: arzuamber-bucket

  iyzico:
    api_key: sandbox-4mlmZxqqpEvkFn61GClqGpDpt0cYZuA2
    secret_key: sandbox-m4UURbHi8klCbIqCiCWsjlyJG8mTfuG4
    base_url: https://sandbox-api.iyzipay.com